
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CADENA ENTERO EXECUTE FDISK FIT ID IGUAL MAYOR_QUE MKDISK NAME PATH REP SIZE TYPE UNITcomandos : comando_mkdisk\n                | comando_execute\n                | comando_rep\n                | empty_production\n                | comando_fdisk\n    empty_production : \n    comando_mkdisk : MKDISK lista_mkdisklista_mkdisk : lista_mkdisk parametros_mkdisk\n                | parametros_mkdiskparametros_mkdisk : param_size\n                | param_unit\n                | param_path\n                | param_fitcomando_execute : EXECUTE lista_executelista_execute : lista_execute parametros_execute\n                | parametros_executeparametros_execute : param_pathcomando_rep : REPcomando_fdisk : FDISK lista_fdisklista_fdisk : lista_fdisk parametros_fdisk\n                | parametros_fdiskparametros_fdisk : param_size\n                | param_unit\n                | param_path\n                | param_name\n                | param_typeparam_size : MAYOR_QUE SIZE IGUAL ENTEROparam_path : MAYOR_QUE PATH IGUAL CADENA\n                |  MAYOR_QUE PATH IGUAL IDparam_unit : MAYOR_QUE UNIT IGUAL CADENA\n                |  MAYOR_QUE UNIT IGUAL IDparam_name : MAYOR_QUE NAME IGUAL CADENA\n                |  MAYOR_QUE NAME IGUAL IDparam_fit : MAYOR_QUE FIT IGUAL CADENA\n                |  MAYOR_QUE FIT IGUAL IDparam_type : MAYOR_QUE TYPE IGUAL CADENA\n                |  MAYOR_QUE TYPE IGUAL ID'
    
_lr_action_items = {'MKDISK':([0,],[7,]),'EXECUTE':([0,],[8,]),'REP':([0,],[9,]),'$end':([0,1,2,3,4,5,6,9,11,12,13,14,15,16,18,19,20,22,23,24,25,26,27,28,30,35,36,45,46,47,48,49,50,51,52,53,54,55,],[-6,0,-1,-2,-3,-4,-5,-18,-7,-9,-10,-11,-12,-13,-14,-16,-17,-19,-21,-22,-23,-24,-25,-26,-8,-15,-20,-27,-30,-31,-28,-29,-34,-35,-32,-33,-36,-37,]),'FDISK':([0,],[10,]),'MAYOR_QUE':([7,8,10,11,12,13,14,15,16,18,19,20,22,23,24,25,26,27,28,30,35,36,45,46,47,48,49,50,51,52,53,54,55,],[17,21,29,17,-9,-10,-11,-12,-13,21,-16,-17,29,-21,-22,-23,-24,-25,-26,-8,-15,-20,-27,-30,-31,-28,-29,-34,-35,-32,-33,-36,-37,]),'SIZE':([17,29,],[31,31,]),'UNIT':([17,29,],[32,32,]),'PATH':([17,21,29,],[33,33,33,]),'FIT':([17,],[34,]),'NAME':([29,],[37,]),'TYPE':([29,],[38,]),'IGUAL':([31,32,33,34,37,38,],[39,40,41,42,43,44,]),'ENTERO':([39,],[45,]),'CADENA':([40,41,42,43,44,],[46,48,50,52,54,]),'ID':([40,41,42,43,44,],[47,49,51,53,55,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'comandos':([0,],[1,]),'comando_mkdisk':([0,],[2,]),'comando_execute':([0,],[3,]),'comando_rep':([0,],[4,]),'empty_production':([0,],[5,]),'comando_fdisk':([0,],[6,]),'lista_mkdisk':([7,],[11,]),'parametros_mkdisk':([7,11,],[12,30,]),'param_size':([7,10,11,22,],[13,24,13,24,]),'param_unit':([7,10,11,22,],[14,25,14,25,]),'param_path':([7,8,10,11,18,22,],[15,20,26,15,20,26,]),'param_fit':([7,11,],[16,16,]),'lista_execute':([8,],[18,]),'parametros_execute':([8,18,],[19,35,]),'lista_fdisk':([10,],[22,]),'parametros_fdisk':([10,22,],[23,36,]),'param_name':([10,22,],[27,27,]),'param_type':([10,22,],[28,28,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> comandos","S'",1,None,None,None),
  ('comandos -> comando_mkdisk','comandos',1,'p_comandos','interprete.py',69),
  ('comandos -> comando_execute','comandos',1,'p_comandos','interprete.py',70),
  ('comandos -> comando_rep','comandos',1,'p_comandos','interprete.py',71),
  ('comandos -> empty_production','comandos',1,'p_comandos','interprete.py',72),
  ('comandos -> comando_fdisk','comandos',1,'p_comandos','interprete.py',73),
  ('empty_production -> <empty>','empty_production',0,'p_empty_production','interprete.py',78),
  ('comando_mkdisk -> MKDISK lista_mkdisk','comando_mkdisk',2,'p_comando_mkdisk','interprete.py',84),
  ('lista_mkdisk -> lista_mkdisk parametros_mkdisk','lista_mkdisk',2,'p_lista_mkdisk','interprete.py',89),
  ('lista_mkdisk -> parametros_mkdisk','lista_mkdisk',1,'p_lista_mkdisk','interprete.py',90),
  ('parametros_mkdisk -> param_size','parametros_mkdisk',1,'p_parametros_mkdisk','interprete.py',98),
  ('parametros_mkdisk -> param_unit','parametros_mkdisk',1,'p_parametros_mkdisk','interprete.py',99),
  ('parametros_mkdisk -> param_path','parametros_mkdisk',1,'p_parametros_mkdisk','interprete.py',100),
  ('parametros_mkdisk -> param_fit','parametros_mkdisk',1,'p_parametros_mkdisk','interprete.py',101),
  ('comando_execute -> EXECUTE lista_execute','comando_execute',2,'p_comando_execute','interprete.py',106),
  ('lista_execute -> lista_execute parametros_execute','lista_execute',2,'p_lista_execute','interprete.py',113),
  ('lista_execute -> parametros_execute','lista_execute',1,'p_lista_execute','interprete.py',114),
  ('parametros_execute -> param_path','parametros_execute',1,'p_parametros_execute','interprete.py',122),
  ('comando_rep -> REP','comando_rep',1,'p_comando_rep','interprete.py',127),
  ('comando_fdisk -> FDISK lista_fdisk','comando_fdisk',2,'p_comando_fdisk','interprete.py',132),
  ('lista_fdisk -> lista_fdisk parametros_fdisk','lista_fdisk',2,'p_lista_fdisk','interprete.py',136),
  ('lista_fdisk -> parametros_fdisk','lista_fdisk',1,'p_lista_fdisk','interprete.py',137),
  ('parametros_fdisk -> param_size','parametros_fdisk',1,'p_parametros_fdisk','interprete.py',145),
  ('parametros_fdisk -> param_unit','parametros_fdisk',1,'p_parametros_fdisk','interprete.py',146),
  ('parametros_fdisk -> param_path','parametros_fdisk',1,'p_parametros_fdisk','interprete.py',147),
  ('parametros_fdisk -> param_name','parametros_fdisk',1,'p_parametros_fdisk','interprete.py',148),
  ('parametros_fdisk -> param_type','parametros_fdisk',1,'p_parametros_fdisk','interprete.py',149),
  ('param_size -> MAYOR_QUE SIZE IGUAL ENTERO','param_size',4,'p_param_size','interprete.py',154),
  ('param_path -> MAYOR_QUE PATH IGUAL CADENA','param_path',4,'p_param_path','interprete.py',158),
  ('param_path -> MAYOR_QUE PATH IGUAL ID','param_path',4,'p_param_path','interprete.py',159),
  ('param_unit -> MAYOR_QUE UNIT IGUAL CADENA','param_unit',4,'p_param_unit','interprete.py',163),
  ('param_unit -> MAYOR_QUE UNIT IGUAL ID','param_unit',4,'p_param_unit','interprete.py',164),
  ('param_name -> MAYOR_QUE NAME IGUAL CADENA','param_name',4,'p_param_name','interprete.py',168),
  ('param_name -> MAYOR_QUE NAME IGUAL ID','param_name',4,'p_param_name','interprete.py',169),
  ('param_fit -> MAYOR_QUE FIT IGUAL CADENA','param_fit',4,'p_param_fit','interprete.py',173),
  ('param_fit -> MAYOR_QUE FIT IGUAL ID','param_fit',4,'p_param_fit','interprete.py',174),
  ('param_type -> MAYOR_QUE TYPE IGUAL CADENA','param_type',4,'p_param_type','interprete.py',178),
  ('param_type -> MAYOR_QUE TYPE IGUAL ID','param_type',4,'p_param_type','interprete.py',179),
]
